#pragma once

int rars_print_int(int value);
int rars_print_string(int address);
int rars_read_int(void);
int rars_read_string(int buffer, int max_length);
int rars_sbrk(int byte_count);
int rars_exit(void);
int rars_print_char(int value);
int rars_read_char(void);
int rars_get_cwd(int buffer, int length);
int rars_time(void);
int rars_time_low(void);
int rars_time_high(void);
int rars_midi_out(int pitch, int duration_ms, int instrument, int volume);
int rars_sleep_ms(int milliseconds);
int rars_midi_out_sync(int pitch, int duration_ms, int instrument, int volume);
int rars_print_int_hex(int value);
int rars_print_int_binary(int value);
int rars_print_uint(int value);
int rars_rand_seed(int generator, int seed);
int rars_rand_int(int generator);
int rars_rand_range(int generator, int upper_bound);
int rars_confirm_dialog(int message);
int rars_input_dialog_int(int message);
int rars_input_dialog_string(int message, int buffer, int max_length);
int rars_message_dialog(int message, int kind);
int rars_message_dialog_int(int message, int value);
int rars_close(int fd);
int rars_message_dialog_string(int message, int value);
int rars_lseek(int fd, int offset, int whence);
int rars_read(int fd, int buffer, int max_length);
int rars_write(int fd, int buffer, int length);
int rars_exit2(int code);
int rars_open(int path, int flags);
